# wrangler.toml
name = "travelai"
type = "javascript"
compatibility_date = "2023-12-01"

[site]
bucket = ".next"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"

# 这是Cloudflare Pages期望的变量
pages_build_output_dir = ".next" 